#!/usr/bin/env bash
# ============================================================================
# ODS — Vast.ai Networking & Access Layer
# ============================================================================
# Part of: p2p-gpu/lib/
# Purpose: Port exposure, Caddy reverse proxy, health page, Cloudflare
#          tunnel, SSH tunnel script, access info display
#
# Expects: LOGFILE, SCRIPT_NAME, log(), warn(), err(), env_set(), env_get(),
#          discover_all_services(), discover_service_ports()
# Provides: expose_ports_for_vastai(), setup_reverse_proxy(),
#           generate_health_page(), setup_cloudflare_tunnel(),
#           generate_ssh_tunnel_script(), generate_powershell_tunnel_script(),
#           print_access_info()
#
# Modder notes:
#   Caddy failure is non-fatal — falls back to SSH tunnel mode.
#   print_access_info is split into sub-functions for maintainability.
#
# SPDX-License-Identifier: Apache-2.0
# ============================================================================

set -euo pipefail

# Rewrite 127.0.0.1 → 0.0.0.0 in compose port bindings for Vast.ai access
expose_ports_for_vastai() {
  local ds_dir="$1"
  # Safety: only rebind on detected P2P GPU providers to avoid
  # accidentally exposing services on non-rented machines.
  if [[ -z "${VAST_TCP_PORT_22:-}" && -z "${PUBLIC_IPADDR:-}" \
        && ! -f /etc/vast.ai && "${PROVIDER_NAME:-}" != "vastai" ]]; then
    warn "Not a detected P2P GPU environment — skipping port rebinding"
    return 0
  fi
  log "Rebinding Docker ports from 127.0.0.1 → 0.0.0.0 for Vast.ai external access"
  local count=0
  while IFS= read -r -d '' compose_file; do
    if grep -q '"127\.0\.0\.1:' "$compose_file"; then
      sed -i 's/"127\.0\.0\.1:/"0.0.0.0:/g' "$compose_file"
      count=$((count + 1))
    fi
  # [NON-FATAL: discovery] Missing compose files just skips port rebinding.
  done < <(find "$ds_dir" -maxdepth 4 \
    \( -name "docker-compose*.yml" -o -name "compose*.yaml" -o -name "compose*.yml" \) \
    -print0 2>&1 || warn "find compose files failed (non-fatal)")
  log "Rebound ports in ${count} compose file(s) to 0.0.0.0"
}

# Deploy Caddy reverse proxy for single-port access
setup_reverse_proxy() {
  local ds_dir="$1"
  local proxy_port="${2:-8080}"
  local env_file="${ds_dir}/.env"

  _install_caddy || return 1
  _generate_caddyfile "$ds_dir" "$proxy_port" "$env_file"
  _start_caddy "$ds_dir" "$proxy_port" "$env_file" || return 1
  _wait_for_proxy_backend "$proxy_port"
}

_install_caddy() {
  command -v caddy &>/dev/null && return 0
  log "Installing Caddy reverse proxy..."
  if apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https 2>>"$LOGFILE" \
    && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
       | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg 2>>"$LOGFILE" \
    && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
       | tee /etc/apt/sources.list.d/caddy-stable.list > /dev/null \
    && apt-get update -qq 2>>"$LOGFILE" \
    && apt-get install -y -qq caddy 2>>"$LOGFILE"; then
    log "Caddy installed successfully"
  else
    warn "Caddy install failed — falling back to SSH tunnel mode"
    return 1
  fi
}

_generate_caddyfile() {
  local ds_dir="$1" proxy_port="$2" env_file="$3"
  local caddy_dir="${ds_dir}/config/caddy"
  mkdir -p "$caddy_dir"

  local webui_port
  webui_port="$(env_get "$env_file" "WEBUI_PORT")"
  webui_port="${webui_port:-3000}"

  # Dashboard is the main ODS panel — it owns the root route.
  # Its nginx serves SPA assets and proxies /api/ → dashboard-api with auth.
  local dashboard_port
  dashboard_port="$(env_get "$env_file" "DASHBOARD_PORT")"
  dashboard_port="${dashboard_port:-3001}"

  cat > "${caddy_dir}/Caddyfile" << CADDYEOF
# ODS reverse proxy — auto-generated by vastai setup
{
  auto_https off
  admin off
}

:${proxy_port} {
  # Dashboard — main ODS panel (root route)
  handle / {
    reverse_proxy 127.0.0.1:${dashboard_port}
  }
  handle /api/* {
    reverse_proxy 127.0.0.1:${dashboard_port}
  }
  handle /assets/* {
    reverse_proxy 127.0.0.1:${dashboard_port}
  }

  # Open WebUI — full access via SSH tunnel (port ${webui_port})
  handle_path /chat/* {
    reverse_proxy 127.0.0.1:${webui_port}
  }

  handle_path /health {
    root * ${caddy_dir}
    file_server
    try_files /health.html
  }

CADDYEOF

  # Append auto-discovered service routes (skip root-handled services)
  while IFS='|' read -r sid port_env port_def _name _cat proxy_mode _startup _cname; do
    [[ -z "$port_env" || "$sid" == "open-webui" || "$sid" == "dashboard" ]] && continue
    local svc_port
    svc_port="$(env_get "$env_file" "$port_env")"
    svc_port="${svc_port:-$port_def}"
    [[ -z "$svc_port" ]] && continue

    if [[ "$proxy_mode" == "root" ]]; then
      printf '  handle /%s/* {\n    reverse_proxy 127.0.0.1:%s\n  }\n\n' \
        "$sid" "$svc_port" >> "${caddy_dir}/Caddyfile"
    else
      printf '  handle_path /%s/* {\n    reverse_proxy 127.0.0.1:%s\n  }\n\n' \
        "$sid" "$svc_port" >> "${caddy_dir}/Caddyfile"
    fi
  done < <(discover_all_services "$ds_dir")

  # Ollama (base service, no manifest)
  local ollama_port
  ollama_port="$(env_get "$env_file" "OLLAMA_PORT")"
  ollama_port="${ollama_port:-8080}"
  cat >> "${caddy_dir}/Caddyfile" << CADDYTAIL
  handle_path /ollama/* {
    reverse_proxy 127.0.0.1:${ollama_port}
  }
  handle_path /v1/* {
    reverse_proxy 127.0.0.1:${ollama_port}
  }
}
CADDYTAIL

  generate_health_page "${caddy_dir}/health.html" "$ds_dir"
}

_start_caddy() {
  local ds_dir="$1" proxy_port="$2" env_file="$3"
  local caddy_dir="${ds_dir}/config/caddy"

  if pgrep -x caddy > /dev/null 2>&1; then
    local old_pid
    old_pid=$(pgrep -x caddy | head -1)
    # [NON-FATAL: cleanup] Old proxy process may have already exited.
    kill "$old_pid" || warn "could not kill old caddy PID ${old_pid} (non-fatal)"
    sleep 1
  fi

  mkdir -p "${ds_dir}/logs"
  nohup caddy run --config "${caddy_dir}/Caddyfile" --adapter caddyfile \
    >> "${ds_dir}/logs/caddy-proxy.log" 2>&1 &
  local caddy_pid=$!
  sleep 2

  if kill -0 "$caddy_pid" 2>&1; then
    log "Caddy reverse proxy running on port ${proxy_port} (PID: ${caddy_pid})"
    env_set "${env_file}" "REVERSE_PROXY_PORT" "$proxy_port"
    return 0
  else
    warn "Caddy failed to start — check ${ds_dir}/logs/caddy-proxy.log"
    return 1
  fi
}

_wait_for_proxy_backend() {
  local proxy_port="$1"
  local elapsed=0 code="000"

  while [[ "$elapsed" -lt 30 ]]; do
    code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 "http://127.0.0.1:${proxy_port}/" || echo "000")
    if [[ "$code" =~ ^[23] ]]; then
      return 0
    fi
    sleep 3
    elapsed=$((elapsed + 3))
  done

  warn "Caddy is running on ${proxy_port}, but dashboard backend is not reachable yet (HTTP ${code})"
  return 1
}

# Generate health dashboard HTML page
generate_health_page() {
  local output_file="$1"
  cat > "$output_file" << 'HEALTHEOF'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ODS — Health</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
           background: #0f1117; color: #e0e0e0; padding: 2rem; }
    h1 { color: #7dd3fc; margin-bottom: 1.5rem; font-size: 1.5rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 1rem; }
    .card { background: #1a1d27; border-radius: 12px; padding: 1rem; border: 1px solid #2a2d37; }
    .card h3 { font-size: 0.95rem; margin-bottom: 0.5rem; }
    .status { display: inline-block; width: 10px; height: 10px; border-radius: 50%; margin-right: 8px; }
    .healthy { background: #22c55e; } .running { background: #eab308; }
    .stopped { background: #6b7280; } .error   { background: #ef4444; }
    .port { color: #7dd3fc; font-size: 0.85rem; }
    .ts { color: #6b7280; font-size: 0.8rem; margin-top: 1rem; }
  </style>
</head>
<body>
  <h1>ODS Health</h1>
  <div class="grid" id="services"><div class="card"><p>Loading...</p></div></div>
  <p class="ts">Auto-refreshes every 15s</p>
  <script>
    async function refresh() {
      try {
        const r = await fetch('/dashboard-api/api/v1/status');
        const data = await r.json();
        const grid = document.getElementById('services');
        grid.innerHTML = '';
        (data.services || []).forEach(s => {
          const cls = s.healthy ? 'healthy' : (s.status === 'running' ? 'running' : 'stopped');
          grid.innerHTML += '<div class="card"><h3><span class="status '+cls+'"></span>'+s.name+'</h3><span class="port">:'+( s.port||'—')+'</span></div>';
        });
      } catch(e) {
        document.getElementById('services').innerHTML =
          '<div class="card"><p>Dashboard API not available.</p></div>';
      }
    }
    refresh(); setInterval(refresh, 15000);
  </script>
</body>
</html>
HEALTHEOF
  log "Generated health dashboard at ${output_file}"
}

# Start Cloudflare Tunnel if token is configured
setup_cloudflare_tunnel() {
  local ds_dir="$1"
  local env_file="${ds_dir}/.env"
  local cf_token
  cf_token="$(env_get "$env_file" "CLOUDFLARE_TUNNEL_TOKEN")"
  [[ -z "$cf_token" ]] && return 0

  log "Cloudflare Tunnel token detected — setting up tunnel"
  if ! command -v cloudflared &>/dev/null; then
    local cf_tmp="/tmp/cloudflared-$$"
    local cf_checksum_url="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.sha256"
    curl -sL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 \
      -o "$cf_tmp" || { warn "cloudflared download failed (non-fatal)"; rm -f "$cf_tmp"; return 0; }
    # Verify checksum when available
    local expected_sha
    expected_sha=$(curl -sL --max-time 10 "$cf_checksum_url" 2>>"$LOGFILE" | awk '{print $1}' || echo "")
    if [[ -n "$expected_sha" ]]; then
      local actual_sha
      actual_sha=$(sha256sum "$cf_tmp" | awk '{print $1}')
      if [[ "$actual_sha" != "$expected_sha" ]]; then
        err "cloudflared checksum mismatch (expected: ${expected_sha:0:12}…, got: ${actual_sha:0:12}…)"
        rm -f "$cf_tmp"
        warn "Skipping Cloudflare tunnel — binary integrity check failed"
        return 0
      fi
      log "cloudflared checksum verified"
    else
      warn "cloudflared checksum not available — skipping integrity check"
    fi
    mv "$cf_tmp" /usr/local/bin/cloudflared
    chmod +x /usr/local/bin/cloudflared
  fi

  local proxy_port
  proxy_port="$(env_get "$env_file" "REVERSE_PROXY_PORT")"
  proxy_port="${proxy_port:-3000}"

  mkdir -p "${ds_dir}/logs"
  # [FIX: cf-token] Pass token via env var, not CLI arg (hidden from ps aux)
  TUNNEL_TOKEN="$cf_token" nohup cloudflared tunnel --no-autoupdate run --token-from-env TUNNEL_TOKEN \
    >> "${ds_dir}/logs/cloudflared.log" 2>&1 &
  local cf_pid=$!
  # [NON-FATAL: pidfile] Missing pidfile only affects teardown cleanup.
  _store_pid "cloudflared" "$cf_pid" 2>>"$LOGFILE" || warn "could not persist cloudflared pid (non-fatal)"
  log "Cloudflare Tunnel started (PID: ${cf_pid}) — HTTPS access active"
}

# Returns 0 when the supplied IP is RFC1918/private or otherwise unusable as a public endpoint.
_is_private_ip() {
  local ip="$1"

  [[ -z "$ip" ]] && return 0

  case "$ip" in
    10.*|172.1[6-9].*|172.2[0-9].*|172.3[0-1].*|192.168.*|169.254.*|127.*) return 0 ;;
    *) return 1 ;;
  esac
}

# Get Vast.ai SSH connection info with proper env var handling
_get_vastai_ssh_info() {
  local host_ip="" ssh_port=""

  # Priority 1: Vast.ai publishes the authoritative public IP here.
  host_ip="${PUBLIC_IPADDR:-}"
  ssh_port="${VAST_TCP_PORT_22:-}"

  # Priority 2: /proc/self/environ (handles SSH sessions that strip env vars)
  if [[ -z "$host_ip" || -z "$ssh_port" ]]; then
    if [[ -r /proc/self/environ ]]; then
      if [[ -z "$host_ip" ]]; then
        host_ip="$(tr '\0' '\n' < /proc/self/environ | grep '^PUBLIC_IPADDR=' | cut -d= -f2 || echo "")"
      fi
      if [[ -z "$ssh_port" ]]; then
        ssh_port="$(tr '\0' '\n' < /proc/self/environ | grep '^VAST_TCP_PORT_22=' | cut -d= -f2 || echo "")"
      fi
    fi
  fi

  # Priority 3: /etc/environment (Vast.ai onstart may export vars here)
  if [[ -z "$host_ip" && -f /etc/environment ]]; then
    host_ip="$(grep '^PUBLIC_IPADDR=' /etc/environment 2>/dev/null | cut -d= -f2 | tr -d '"' || echo "")"  # stderr expected: file may be absent or unreadable
  fi
  if [[ -z "$ssh_port" && -f /etc/environment ]]; then
    ssh_port="$(grep '^VAST_TCP_PORT_22=' /etc/environment 2>/dev/null | cut -d= -f2 | tr -d '"' || echo "")"  # stderr expected: file may be absent or unreadable
  fi

  # Discard any detected private/NAT address.
  if _is_private_ip "$host_ip"; then
    host_ip=""
  fi

  # Priority 4: External IP detection (reliable fallback)
  if [[ -z "$host_ip" ]]; then
    host_ip="$(curl -sf --max-time 5 ifconfig.me 2>>"$LOGFILE" || curl -sf --max-time 5 icanhazip.com 2>>"$LOGFILE" || echo '<your-vast-ip>')"
  fi
  if [[ -z "$ssh_port" ]]; then
    ssh_port="22"
  fi

  echo "${host_ip}|${ssh_port}"
}

# Generate auto-reconnecting SSH tunnel script
generate_ssh_tunnel_script() {
  local ds_dir="$1"
  local host_ip ssh_port
  IFS='|' read -r host_ip ssh_port <<< "$(_get_vastai_ssh_info)"

  local env_file="${ds_dir}/.env"
  local entry_port
  entry_port="$(env_get "$env_file" "DASHBOARD_PORT")"
  entry_port="${entry_port:-3001}"
  local local_proxy_port="58080"

  local script_path="${ds_dir}/connect-tunnel.sh"
  {
    echo '#!/usr/bin/env bash'
    echo '# ODS — auto-reconnecting SSH tunnel (run on YOUR LOCAL machine)'
    echo "HOST=\"${host_ip}\""
    echo "SSH_PORT=\"${ssh_port}\""
    echo "ENTRY_PORT=\"${entry_port}\""
    echo '_uname="$(uname -s | tr "[:upper:]" "[:lower:]")"'
    echo 'case "${_uname}" in'
    echo "  mingw*|msys*|cygwin*) _default_local_proxy=${local_proxy_port} ;;"
    echo "  *) _default_local_proxy=${local_proxy_port} ;;"
    echo 'esac'
    echo 'LOCAL_PROXY_PORT="${LOCAL_PROXY_PORT:-${_default_local_proxy}}"'
    echo 'if [[ "${FULL_TUNNEL:-0}" == "1" ]]; then'
    echo '  FORWARDS="-L ${LOCAL_PROXY_PORT}:127.0.0.1:${ENTRY_PORT}'
    discover_service_ports "$ds_dir" | while IFS='|' read -r key port _label; do
      [[ "$key" == "REVERSE_PROXY_PORT" ]] && continue
      local_port="$port"
      [[ "$port" -lt 1024 ]] && local_port=$((10000 + port))
      echo "    -L ${local_port}:127.0.0.1:${port}"
    done
    echo '  "'
    echo 'else'
    echo '  FORWARDS="-L ${LOCAL_PROXY_PORT}:127.0.0.1:${ENTRY_PORT}"'
    echo 'fi'
    echo 'DELAY=5'
    echo 'while true; do'
    echo '  ssh -N -o ServerAliveInterval=15 -o ServerAliveCountMax=3 \'
    echo '      -o ExitOnForwardFailure=yes \'
    echo '      -p "$SSH_PORT" $FORWARDS root@"$HOST"'
    echo '  echo "[!] Connection lost. Reconnecting in ${DELAY}s..."'
    echo '  sleep "$DELAY"'
    echo '  DELAY=$(( DELAY < 60 ? DELAY * 2 : 60 ))'
    echo 'done'
  } > "$script_path"
  chmod +x "$script_path"
  log "Generated auto-reconnecting tunnel script: ${script_path}"
}

generate_powershell_tunnel_script() {
  local ds_dir="$1"
  local host_ip ssh_port
  IFS='|' read -r host_ip ssh_port <<< "$(_get_vastai_ssh_info)"

  local env_file="${ds_dir}/.env"
  local entry_port
  entry_port="$(env_get "$env_file" "DASHBOARD_PORT")"
  entry_port="${entry_port:-3001}"
  local local_proxy_port="58080"

  local script_path="${ds_dir}/connect-tunnel.ps1"
  {
    cat << POWERSHELL_HEAD
param(
  [int]\$LocalProxyPort = ${local_proxy_port},
  [int]\$ReconnectDelay = 5,
  [string]\$Host = "${host_ip}",
  [int]\$SshPort = ${ssh_port}
)

\$EntryPort = ${entry_port}
while (\$true) {
  \$Forwards = @(
    "-L"; "\${LocalProxyPort}:127.0.0.1:\$EntryPort";
POWERSHELL_HEAD
    discover_service_ports "$ds_dir" | while IFS='|' read -r key port _label; do
      [[ "$key" == "REVERSE_PROXY_PORT" ]] && continue
      lp="$port"
      [[ "$port" -lt 1024 ]] && lp=$((10000 + port))
      printf '    "-L"; "%s:127.0.0.1:%s";\n' "$lp" "$port"
    done
    cat << 'POWERSHELL_TAIL'
  )
  ssh -N -o ServerAliveInterval=15 -o ServerAliveCountMax=3 -o ExitOnForwardFailure=yes -p $SshPort @Forwards "root@$Host"
  Write-Host "[!] Connection lost. Reconnecting in ${ReconnectDelay}s..."
  Start-Sleep -Seconds $ReconnectDelay
  if ($ReconnectDelay -lt 60) {
    $ReconnectDelay = [Math]::Min($ReconnectDelay * 2, 60)
  }
}
POWERSHELL_TAIL
  } > "$script_path"
  log "Generated PowerShell tunnel script: ${script_path}"
}

# ── Print access info (split into sub-functions) ───────────────────────────
print_access_info() {
  local ds_dir="$1"
  local env_file="${ds_dir}/.env"
  local host_ip ssh_port
  local dash_api_status dashboard_status webui_status
  IFS='|' read -r host_ip ssh_port <<< "$(_get_vastai_ssh_info)"
  dash_api_status=$(docker inspect --format '{{.State.Status}}' ods-dashboard-api 2>/dev/null || echo "missing") # stderr expected: container may not exist
  dashboard_status=$(docker inspect --format '{{.State.Status}}' ods-dashboard 2>/dev/null || echo "missing") # stderr expected: container may not exist
  webui_status=$(
    docker inspect --format '{{.State.Status}}' ods-webui 2>/dev/null || # stderr expected: container may not exist
    docker inspect --format '{{.State.Status}}' ods-webui 2>/dev/null || # stderr expected: container may not exist
    echo "missing"
  )

  echo ""
  if [[ "$dash_api_status" == "running" && ( "$dashboard_status" == "running" || "$webui_status" == "running" ) ]]; then
    echo -e "${CYAN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}${BOLD}  ODS is ready on Vast.ai!${NC}"
    echo -e "${CYAN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  else
    echo -e "${YELLOW}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${YELLOW}${BOLD}  ODS access info (core services still starting)${NC}"
    echo -e "${YELLOW}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  fi
  echo ""
  echo -e "${BOLD}Working directory:${NC} ${ds_dir}"
  echo -e "${BOLD}Setup log:${NC}         ${LOGFILE}"
  echo ""

  _print_ssh_section "$ds_dir" "$env_file" "$host_ip" "$ssh_port"
  _print_service_list "$ds_dir"
  _print_model_upload_help "$ds_dir" "$host_ip" "$ssh_port"
  _print_commands_help "$ds_dir"
}

_print_proxy_section() {
  local ds_dir="$1" env_file="$2" host_ip="$3"
  local proxy_port root_code proxy_ready="false"
  proxy_port="$(env_get "$env_file" "REVERSE_PROXY_PORT")"
  if [[ -n "$proxy_port" ]] && pgrep -x caddy > /dev/null 2>&1; then
    root_code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 3 "http://127.0.0.1:${proxy_port}/" || echo "000")
    [[ "$root_code" =~ ^[23] ]] && proxy_ready="true"

    # On Vast.ai, the container's internal port is remapped to a random
    # external port exposed in VAST_TCP_PORT_<internal>. If that var exists,
    # the public URL must use the mapped port — not the internal one.
    local ext_port_var="VAST_TCP_PORT_${proxy_port}"
    local ext_port="${!ext_port_var:-}"
    if [[ "$proxy_ready" == "true" ]]; then
      echo -e "${GREEN}${BOLD}▸ Reverse Proxy Active (single-port access!)${NC}"
    else
      echo -e "${YELLOW}${BOLD}▸ Reverse proxy process is running (backends still starting)${NC}"
    fi
    echo ""
    if [[ -n "$ext_port" ]]; then
      echo -e "  ${BOLD}Public (Vast.ai mapped):${NC}"
      echo -e "    Dashboard:    ${BOLD}http://${host_ip}:${ext_port}/${NC}"
      echo "    Open WebUI:     http://${host_ip}:${ext_port}/chat/"
      echo "    n8n Workflows:  http://${host_ip}:${ext_port}/n8n/"
      echo "    Health Status:  http://${host_ip}:${ext_port}/health"
      echo ""
      echo -e "  ${DIM}(Internal port ${proxy_port} is remapped by Vast.ai to ${ext_port}.)${NC}"
    else
      echo -e "  Dashboard:    ${BOLD}http://${host_ip}:${proxy_port}/${NC}"
      echo "    Open WebUI:     http://${host_ip}:${proxy_port}/chat/"
      echo "    n8n Workflows:  http://${host_ip}:${proxy_port}/n8n/"
      echo "    Health Status:  http://${host_ip}:${proxy_port}/health"
      echo ""
      echo -e "  ${YELLOW}Note:${NC} no VAST_TCP_PORT_${proxy_port} env var was found."
      echo -e "  If the URL above is unreachable, the Vast.ai instance didn't expose"
      echo -e "  port ${proxy_port}. Either:"
      echo -e "    • Edit the instance → add ${proxy_port} to 'On-start script' port list, or"
      echo -e "    • Use the SSH tunnel below (always works)."
    fi

    if [[ "$proxy_ready" != "true" ]]; then
      echo ""
      echo -e "  ${YELLOW}Warning:${NC} proxy is listening, but dashboard/open-webui backends are not healthy yet."
      echo -e "  Run: ${BOLD}bash ${SCRIPT_NAME} --fix${NC}"
    fi

    echo ""
  fi
}

_print_ssh_section() {
  local ds_dir="$1" env_file="$2" host_ip="$3" ssh_port="$4"
  echo -e "${BOLD}━━━ SSH Tunnel (recommended for Vast.ai) ━━━${NC}"
  echo ""

  local tunnel_flags=""
  local remapped_notes=""
  local entry_port windows_local_proxy_port
  entry_port="$(env_get "$env_file" "DASHBOARD_PORT")"
  entry_port="${entry_port:-3001}"
  windows_local_proxy_port="58080"

  while IFS='|' read -r key port _label; do
    [[ "$key" == "REVERSE_PROXY_PORT" ]] && continue
    local local_port="$port"
    if [[ "$port" -lt 1024 ]]; then
      local_port=$((10000 + port))
      remapped_notes="${remapped_notes}\n  ${DIM}  Port ${port} remapped to local ${local_port} (ports <1024 need admin)${NC}"
    fi
    tunnel_flags="${tunnel_flags} -L ${local_port}:127.0.0.1:${port}"
  done < <(discover_service_ports "$ds_dir")

  echo -e "  ${BOLD}Windows PowerShell (all ports, recommended):${NC}"
  echo -e "${DIM}ssh -N -o ExitOnForwardFailure=yes -p ${ssh_port} -i \$env:USERPROFILE\\.ssh\\id_ed25519 -L ${windows_local_proxy_port}:127.0.0.1:${entry_port}${tunnel_flags} root@${host_ip}${NC}"
  echo -e "${DIM}Open dashboard: http://127.0.0.1:3001/${NC}"
  echo -e "${DIM}Easy alias:    http://127.0.0.1:${windows_local_proxy_port}/${NC}"
  echo ""

  echo -e "  ${BOLD}Linux / macOS (all ports):${NC}"
  echo -e "${DIM}ssh -N -p ${ssh_port} -i ~/.ssh/id_ed25519 -L ${windows_local_proxy_port}:127.0.0.1:${entry_port}${tunnel_flags} root@${host_ip}${NC}"
  echo -e "${DIM}Open dashboard: http://127.0.0.1:3001/${NC}"
  echo ""

  echo -e "  ${BOLD}Auto-reconnect scripts:${NC}"
  echo -e "  ${DIM}Windows: scp -P ${ssh_port} root@${host_ip}:${ds_dir}/connect-tunnel.ps1 .${NC}"
  echo -e "  ${DIM}         powershell -ExecutionPolicy Bypass -File .\\connect-tunnel.ps1${NC}"
  echo -e "  ${DIM}Linux/macOS/WSL: scp -P ${ssh_port} root@${host_ip}:${ds_dir}/connect-tunnel.sh .${NC}"
  echo -e "  ${DIM}                 FULL_TUNNEL=1 bash connect-tunnel.sh${NC}"
  echo ""
  echo -e "  ${DIM}If Windows reports \"bind [127.0.0.1]:PORT: Permission denied\",${NC}"
  echo -e "  ${DIM}that local port is reserved by Hyper-V/WinNAT. Use a different local port:${NC}"
  echo -e "  ${DIM}  -L 58080:127.0.0.1:${entry_port}   (or any free high port)${NC}"
  echo -e "  ${DIM}Optional admin fix:${NC}"
  echo -e "  ${DIM}  net stop winnat; net start winnat   (run PowerShell as admin)${NC}"
  echo -e "  ${DIM}Check excluded ranges: netsh int ipv4 show excludedportrange protocol=tcp${NC}"
  echo -e "  ${DIM}If you see \"channel N: open failed: connect failed: Connection refused\",${NC}"
  echo -e "  ${DIM}the SSH tunnel is up, but that specific remote service is not listening yet.${NC}"
  echo ""

  if [[ -n "$remapped_notes" ]]; then
    echo -e "${BOLD}  Remapped privileged ports:${NC}"
    echo -e "$remapped_notes"
    echo ""
  fi

}

_print_service_list() {
  local ds_dir="$1"
  echo -e "${BOLD}Services:${NC}"
  discover_service_ports "$ds_dir" | while IFS='|' read -r key port label; do
    [[ "$key" == "REVERSE_PROXY_PORT" ]] && continue
    printf "  %-22s http://localhost:%s\n" "${label}:" "${port}"
  done
  echo ""
}

_print_model_upload_help() {
  local ds_dir="$1" host_ip="$2" ssh_port="$3"
  echo -e "${BOLD}Upload Custom Models:${NC}"
  echo "  scp -P ${ssh_port} my-model.gguf root@${host_ip}:${ds_dir}/data/models/"
  echo "  # Then: edit .env GGUF_FILE=my-model.gguf && docker restart ods-llama-server"
  echo ""
}

_print_commands_help() {
  local ds_dir="$1"
  local script_name="${SCRIPT_NAME:-setup.sh}"
  echo -e "${BOLD}Commands:${NC}"
  echo "  bash ${script_name} --status     # Check health"
  echo "  bash ${script_name} --info       # Connection details"
  echo "  bash ${script_name} --fix        # Apply fixes + restart"
  echo "  bash ${script_name} --resume     # Quick restart after SSH drop"
  echo "  bash ${script_name} --teardown   # Stop all services"
  echo ""
}
