#!/usr/bin/env bash
# ============================================================================
# ODS — P2P GPU Service Discovery & Management
# ============================================================================
# Part of: ods/installers/p2p-gpu/lib/
# Purpose: Manifest-driven service discovery, port enumeration, compose
#          command detection, Docker image pre-pull, service startup
#
# Expects: ODS_USER, LOGFILE, log(), warn(), err(), env_get(), env_set(),
#          expose_ports_for_vastai()
# Provides: read_manifest_field(), discover_all_services(),
#           discover_service_ports(), extract_compose_uid(),
#           get_compose_cmd(), start_services(), prepull_docker_images()
#
# Modder notes:
#   Requires python3 + PyYAML (installed in Phase 1). Functions gracefully
#   return empty when python3/PyYAML is unavailable.
#   [FIX: python-except] Python catches only specific exceptions with logging.
#
# SPDX-License-Identifier: Apache-2.0
# ============================================================================

set -euo pipefail

# Resolve ods-network gateway for host-agent binding.
_resolve_dream_network_gateway() {
  local gateway
  gateway=$(docker network inspect ods-network \
    --format '{{(index .IPAM.Config 0).Gateway}}' 2>>"$LOGFILE" | head -1 || echo "")
  gateway=$(echo "$gateway" | xargs)
  if [[ "$gateway" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    echo "$gateway"
    return 0
  fi
  return 1
}

_is_loopback_addr() {
  case "$1" in
    ""|"127.0.0.1"|"localhost"|"::1") return 0 ;;
    *) return 1 ;;
  esac
}

_restart_host_agent() {
  local ds_dir="$1"
  local ods_cli="${ds_dir}/ods-cli"

  if [[ ! -x "$ods_cli" ]]; then
    warn "ods-cli not found at ${ods_cli} — skipping host agent restart"
    return 1
  fi

  # [NON-FATAL: host-agent] Restart can be retried manually if it fails.
  su - "$ODS_USER" -c "cd ${ds_dir} && ODS_HOME=${ds_dir} ./ods-cli agent restart" \
    >> "$LOGFILE" 2>&1 || { warn "Host agent restart failed (non-fatal)"; return 1; }
  return 0
}

# Ensure host agent binds to the Dream network gateway so containers can reach it.
_ensure_host_agent_network_binding() {
  local ds_dir="$1"
  local env_file="${ds_dir}/.env"
  [[ ! -f "$env_file" ]] && return 0

  local gateway
  gateway=$(_resolve_dream_network_gateway) || return 0

  local bind host updated=false
  bind="$(env_get "$env_file" "ODS_AGENT_BIND")"
  host="$(env_get "$env_file" "ODS_AGENT_HOST")"

  if _is_loopback_addr "$bind"; then
    env_set "$env_file" "ODS_AGENT_BIND" "$gateway"
    updated=true
  fi
  if _is_loopback_addr "$host"; then
    env_set "$env_file" "ODS_AGENT_HOST" "$gateway"
    updated=true
  fi

  if [[ "$updated" == "true" ]]; then
    log "Pinned host agent binding to ods-network gateway ${gateway}"
    _restart_host_agent "$ds_dir" || warn "Host agent restart after bind update failed (non-fatal)"
  fi
}

# Generate a p2p-gpu compose overlay that fixes multi-GPU device reservation
# and passes GPU assignment env vars that the upstream multigpu overlay omits.
# Only generated when GPU_COUNT >= 2 and GPU_BACKEND is nvidia.
# The overlay is appended to compose_flags so it merges on top of whatever
# the upstream resolver selected.
_generate_p2p_gpu_overlay() {
  local ds_dir="$1"
  local overlay="${ds_dir}/docker-compose.p2p-gpu.yml"
  local backend="${GPU_BACKEND:-}"

  if [[ "${GPU_COUNT:-0}" -lt 2 ]]; then
    if [[ -f "$overlay" ]]; then
      # [NON-FATAL: overlay] Cleanup failure should not block install flow.
      rm -f "$overlay" || warn "Failed to remove p2p-gpu overlay (non-fatal)"
    fi
    return 0
  fi

  if [[ -z "$backend" ]]; then
    backend=$(detect_gpu_backend)
  fi

  if [[ "$backend" == "nvidia" ]]; then
    cat > "$overlay" << 'P2P_OVERLAY_EOF'
# Auto-generated by p2p-gpu toolkit - do not edit manually.
# Ensures multi-GPU device reservation and GPU assignment env vars.
services:
  llama-server:
    environment:
      LLAMA_ARG_MAIN_GPU: "${LLAMA_ARG_MAIN_GPU:-}"
      GGML_CUDA_P2P: "${GGML_CUDA_P2P:-}"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
P2P_OVERLAY_EOF
  elif [[ "$backend" == "amd" ]]; then
    cat > "$overlay" << 'P2P_OVERLAY_EOF'
# Auto-generated by p2p-gpu toolkit - do not edit manually.
services:
  llama-server:
    environment:
      LLAMA_ARG_TENSOR_SPLIT: "${LLAMA_ARG_TENSOR_SPLIT:-}"
P2P_OVERLAY_EOF
  else
    if [[ -f "$overlay" ]]; then
      # [NON-FATAL: overlay] Cleanup failure should not block install flow.
      rm -f "$overlay" || warn "Failed to remove p2p-gpu overlay (non-fatal)"
    fi
    return 0
  fi

  if [[ -f "$overlay" ]]; then
    # [NON-FATAL: overlay] Ownership fix failure should not block compose usage.
    chown "${ODS_USER}:${ODS_USER}" "$overlay" || warn "Overlay ownership fix failed (non-fatal)"
    # [NON-FATAL: overlay] Mode fix failure should not block compose usage.
    chmod 0644 "$overlay" || warn "Overlay chmod failed (non-fatal)"
    log "Generated p2p-gpu compose overlay: ${overlay}"
  fi
}

# Ensure Dream host agent is running so Dashboard model downloads can start.
_ensure_host_agent_running() {
  local ds_dir="$1"
  local ods_cli="${ds_dir}/ods-cli"
  local agent_port agent_bind
  local agent_probe

  if [[ ! -x "$ods_cli" ]]; then
    warn "ods-cli not found at ${ods_cli} — skipping host agent auto-start"
    return 0
  fi

  agent_port="$(grep '^ODS_AGENT_PORT=' "${ds_dir}/.env" 2>/dev/null | cut -d= -f2 | tr -d '[:space:]' || echo "7710")"  # stderr expected: .env may not exist
  agent_port="${agent_port:-7710}"
  agent_bind="$(grep '^ODS_AGENT_BIND=' "${ds_dir}/.env" 2>/dev/null | cut -d= -f2 | tr -d '[:space:]' || echo "127.0.0.1")"  # stderr expected: .env may not exist
  agent_bind="${agent_bind:-127.0.0.1}"
  agent_probe="$agent_bind"
  if [[ "$agent_probe" == "0.0.0.0" || "$agent_probe" == "::" ]]; then
    agent_probe="127.0.0.1"
  fi

  if curl -sf --max-time 2 "http://${agent_probe}:${agent_port}/health" >/dev/null 2>&1; then
    log "Host agent already running on port ${agent_port}"
    return 0
  fi

  if ! command -v python3 &>/dev/null; then
    warn "python3 not found — host agent cannot start"
    warn "Install: apt-get install -y python3"
    return 1
  fi

  local agent_script="${ds_dir}/bin/ods-host-agent.py"
  if [[ ! -f "$agent_script" ]]; then
    warn "Agent script not found at ${agent_script} — skipping"
    return 1
  fi

  local attempt pid_file="${ds_dir}/data/ods-host-agent.pid" wait_elapsed
  for attempt in 1 2; do
    log "Starting host agent (attempt ${attempt}/2)..."
    # [NON-FATAL: host-agent] Start failure can be retried or handled manually.
    su - "$ODS_USER" -c "cd ${ds_dir} && ODS_HOME=${ds_dir} ./ods-cli agent start" \
      >> "$LOGFILE" 2>&1 || warn "ods-cli agent start returned non-zero (attempt ${attempt})"

    wait_elapsed=0
    while [[ $wait_elapsed -lt 20 ]]; do
      sleep 3
      wait_elapsed=$((wait_elapsed + 3))
      if curl -sf --max-time 2 "http://${agent_probe}:${agent_port}/health" >/dev/null 2>&1; then
        log "Host agent verified running on port ${agent_port} (attempt ${attempt})"
        return 0
      fi
    done

    if [[ $attempt -eq 1 ]]; then
      warn "Host agent not responding after start — retrying..."
      if [[ -f "$pid_file" ]]; then
        # [NON-FATAL: cleanup] Stale pid cleanup should not block host agent retry.
        kill "$(cat "$pid_file")" 2>>"$LOGFILE" || warn "stale host agent pid in ${pid_file} could not be killed"
        rm -f "$pid_file"
      fi
    fi
  done

  warn "Host agent failed to start after 2 attempts"
  warn "Manual start: su - ${ODS_USER} -c 'cd ${ds_dir} && ODS_HOME=${ds_dir} ./ods-cli agent start'"
  warn "Check logs: cat ${ds_dir}/data/ods-host-agent.log"
  return 1
}

# Ensure OpenCode web is reachable on no-systemd hosts (Vast.ai fallback).
_ensure_opencode_web_running() {
  local ds_dir="$1"
  local env_file="${ds_dir}/.env"
  local opencode_bin="/home/${ODS_USER}/.opencode/bin/opencode"
  local opencode_port opencode_password escaped_password launch_dir escaped_launch_dir

  opencode_port=$(env_get "$env_file" "OPENCODE_PORT")
  opencode_port="${opencode_port:-3003}"

  if curl -sf --max-time 3 "http://127.0.0.1:${opencode_port}/" >/dev/null 2>&1; then
    log "OpenCode web already reachable on port ${opencode_port}"
    return 0
  fi

  if [[ ! -x "$opencode_bin" ]]; then
    warn "OpenCode binary not found at ${opencode_bin} — skipping OpenCode web auto-start"
    return 0
  fi

  opencode_password=$(env_get "$env_file" "OPENCODE_SERVER_PASSWORD")
  if [[ -z "$opencode_password" ]]; then
    opencode_password=$(openssl rand -base64 16)
    env_set "$env_file" "OPENCODE_SERVER_PASSWORD" "$opencode_password"
    log "Generated OPENCODE_SERVER_PASSWORD for secure OpenCode web access"
  fi

  launch_dir="$ds_dir"
  if ! su - "$ODS_USER" -c "test -r $(printf '%q' "$ds_dir") && test -x $(printf '%q' "$ds_dir")"; then
    launch_dir="$ODS_HOME"
    warn "OpenCode launch dir ${ds_dir} is not accessible to ${ODS_USER}; using ${launch_dir}"
  fi

  mkdir -p "${ds_dir}/logs"
  escaped_password=$(printf '%q' "$opencode_password")
  escaped_launch_dir=$(printf '%q' "$launch_dir")
  if su - "$ODS_USER" -c \
    "cd ${escaped_launch_dir} && OPENCODE_SERVER_PASSWORD=${escaped_password} nohup ${opencode_bin} web --hostname 0.0.0.0 --port ${opencode_port} >> ${ds_dir}/logs/opencode-web.log 2>&1 &" \
    >> "$LOGFILE" 2>&1; then
    sleep 2
    if curl -sf --max-time 4 "http://127.0.0.1:${opencode_port}/" >/dev/null 2>&1; then
      log "Started OpenCode web fallback on port ${opencode_port}"
    else
      warn "OpenCode fallback launch command succeeded but service is not reachable yet"
    fi
  else
    warn "OpenCode fallback launch failed (non-fatal)"
  fi
}

_normalize_dashboard_api_port_envs() {
  local env_file="$1"

  [[ -f "$env_file" ]] || return 0

  python3 - "$env_file" <<'PY'
from pathlib import Path
import re
import sys

path = Path(sys.argv[1])
text = path.read_text()
pattern = re.compile(r'^([A-Z0-9_]+_PORT)=(\d+)\s+#.*$')
changed = []
lines = []

for line in text.splitlines():
    match = pattern.match(line)
    if match:
      line = f"{match.group(1)}={match.group(2)}"
      changed.append(match.group(1))
    lines.append(line)

new_text = "\n".join(lines) + ("\n" if text.endswith("\n") else "")
if new_text != text:
    path.write_text(new_text)
    if changed:
        print("\n".join(changed))
PY
}

# Read a field from a manifest.yaml service: block
read_manifest_field() {
  local manifest="$1" field="$2"
  # [NON-FATAL: discovery] A single bad manifest should not block others.
  python3 -c "
import yaml, sys
try:
    data = yaml.safe_load(open(sys.argv[1]))
    svc = data.get('service') or {}
    val = svc.get(sys.argv[2], '')
    if isinstance(val, list):
        print(' '.join(str(v) for v in val))
    else:
        print(val)
except yaml.YAMLError as e:
    print(f'YAML parse error in {sys.argv[1]}: {e}', file=sys.stderr)
except OSError as e:
  print(f'File read error {sys.argv[1]}: {e}', file=sys.stderr)
" "$manifest" "$field" || warn "manifest field read failed for ${manifest}:${field} (non-fatal)"
}

# Discover all enabled services from extension manifests.
# Usage: discover_all_services <ds_dir> [hints_file]
# Output: ID|PORT_ENV|PORT_DEFAULT|NAME|CATEGORY|PROXY_MODE|STARTUP_BEHAVIOR|CONTAINER_NAME
discover_all_services() {
  local ds_dir="$1"
  local hints_file="${2:-}"
  if [[ -z "$hints_file" && -n "${SCRIPT_DIR:-}" ]]; then
    hints_file="${SCRIPT_DIR}/config/service-hints.yaml"
  fi
  local ext_dirs=("${ds_dir}/extensions/services" "${ds_dir}/user-extensions")

  for ext_root in "${ext_dirs[@]}"; do
    [[ ! -d "$ext_root" ]] && continue
    for manifest in "${ext_root}"/*/manifest.yaml; do
      [[ ! -f "$manifest" ]] && continue
          # [NON-FATAL: discovery] A single bad manifest should not block others.
          python3 -c "import os, yaml, sys; data = yaml.safe_load(open(sys.argv[1])) or {}; svc = data.get('service') or {}; sid = svc.get('id', ''); port_env = svc.get('external_port_env', ''); port_def = svc.get('external_port_default', ''); name = svc.get('name', sid); cat = svc.get('category', 'optional'); hints = {}; hints_path = sys.argv[2] if len(sys.argv) > 2 else ''; hints = ((yaml.safe_load(open(hints_path)) or {}).get(sid, {}) if (hints_path and os.path.exists(hints_path) and sid) else {}); proxy = hints.get('proxy_mode', svc.get('proxy_mode', 'simple')); startup = hints.get('startup_behavior', svc.get('startup_behavior', 'normal')); cname = svc.get('container_name', ''); htimeout = svc.get('health_timeout', 0); startup = 'heavy' if startup == 'normal' and isinstance(htimeout, (int, float)) and htimeout > 20 else startup; print(f'{sid}|{port_env}|{port_def}|{name}|{cat}|{proxy}|{startup}|{cname}') if sid else None" "$manifest" "$hints_file" || warn "service discovery failed for ${manifest} (non-fatal)"
    done
  done
}

# Discover service ports from .env / manifests.
# Output: SERVICE_KEY|PORT_NUMBER|LABEL
# Reads explicit _PORT= lines from .env, then fills in manifest defaults
# for any services whose port_env isn't already set.
discover_service_ports() {
  local ds_dir="$1"
  local env_file="${ds_dir}/.env"
  local env_example="${ds_dir}/.env.example"

  declare -A PORT_LABELS PORT_DEFAULTS SEEN_KEYS
  while IFS='|' read -r _id port_env port_def svc_name _rest; do
    [[ -z "$port_env" ]] && continue
    PORT_LABELS["$port_env"]="$svc_name"
    [[ -n "$port_def" ]] && PORT_DEFAULTS["$port_env"]="$port_def"
  done < <(discover_all_services "$ds_dir")

  local source_file="$env_file"
  [[ ! -f "$source_file" ]] && source_file="$env_example"
  [[ ! -f "$source_file" ]] && return 0

  # Emit ports explicitly set in .env
  awk -F= '/^[A-Z_]+_PORT=/{print}' "$source_file" | while IFS='=' read -r key value; do
    value=$(echo "$value" | sed 's/[[:space:]]#.*$//' | tr -d '"' | tr -d "'" | xargs)
    [[ -z "$value" ]] && continue
    local label="${PORT_LABELS[$key]:-$key}"
    echo "${key}|${value}|${label}"
  done

  # Track which keys were already emitted
  while IFS= read -r key; do
    SEEN_KEYS["$key"]=1
  done < <(awk -F= '/^[A-Z_]+_PORT=/{print $1}' "$source_file")

  # Fill in manifest defaults for services not in .env
  for key in "${!PORT_DEFAULTS[@]}"; do
    [[ -n "${SEEN_KEYS[$key]:-}" ]] && continue
    local label="${PORT_LABELS[$key]:-$key}"
    echo "${key}|${PORT_DEFAULTS[$key]}|${label}"
  done
}

# Detect available compose command
get_compose_cmd() {
  if docker compose version &>/dev/null; then
    echo "docker compose"
  elif command -v docker-compose &>/dev/null; then
    echo "docker-compose"
  else
    err "Neither 'docker compose' nor 'docker-compose' found"
    exit 1
  fi
}

# Pre-pull Docker images in parallel
prepull_docker_images() {
  local ds_dir="$1"
  local max_parallel="${2:-4}"

  local images
  images=$(grep -rh 'image:' "${ds_dir}"/docker-compose*.yml \
    "${ds_dir}"/extensions/services/*/compose*.y*ml 2>&1 \
    | sed -E 's/.*image:\s*//' | tr -d '"' | tr -d "'" \
    | sort -u | grep -v '^\$' || echo "")

  if [[ -z "$images" ]]; then
    log "No Docker images found to pre-pull"
    return 0
  fi

  local count
  count=$(echo "$images" | wc -l)
  log "Pre-pulling ${count} Docker images (${max_parallel} parallel)..."

  # [NON-FATAL: images] Images can be pulled later during compose up.
  echo "$images" | xargs -P "$max_parallel" -I {} sh -c \
    'docker pull {} >/dev/null 2>&1 && echo "  pulled: {}" || echo "  skip:   {} (will retry at compose up)"' \
    || warn "some image pulls failed (non-fatal)"

  log "Docker image pre-pull complete"
}

# ── Remove stale Docker network ────────────────────────────────────────────
_cleanup_stale_network() {
  if ! docker network inspect ods-network >/dev/null 2>&1; then
    return 0
  fi
  local net_label
  net_label=$(docker network inspect ods-network \
    --format '{{index .Labels "com.docker.compose.network"}}' 2>&1 || echo "")
  if [[ -n "$net_label" ]]; then
    return 0
  fi
  log "Removing stale ods-network (missing compose labels)..."
  for cid in $(docker network inspect ods-network \
    -f '{{range .Containers}}{{.Name}} {{end}}' 2>&1 || echo ""); do
    # [NON-FATAL: cleanup] Best-effort teardown — partial cleanup is better than none.
    docker network disconnect -f ods-network "$cid" || warn "disconnect ${cid} failed (non-fatal)"
  done
  # [NON-FATAL: cleanup] Best-effort teardown — partial cleanup is better than none.
  docker network rm ods-network || warn "network rm failed (non-fatal)"
}

_set_safe_llama_cpu_caps() {
  local env_file="$1" max_cpu="$2"
  [[ ! -f "$env_file" ]] && return 0

  local llama_limit="${max_cpu}.0"
  local llama_reservation="2.0"
  if [[ "$max_cpu" -lt 2 ]]; then
    llama_reservation="1.0"
  fi

  env_set "$env_file" "LLAMA_CPU_LIMIT" "$llama_limit"
  env_set "$env_file" "LLAMA_CPU_RESERVATION" "$llama_reservation"
}

_extract_cpu_ceiling_from_compose_error() {
  local compose_err="$1"
  local ceiling=""

  ceiling=$(tr -d '\r' < "$compose_err" | grep -Eo 'range of CPUs is from [0-9.]+ to [0-9.]+' 2>>"$LOGFILE" \
    | head -1 | awk '{print $NF}' | cut -d'.' -f1 || echo "")

  if [[ -z "$ceiling" ]]; then
    ceiling=$(tr -d '\r' < "$compose_err" | grep -Eo 'only [0-9]+ CPUs available' 2>>"$LOGFILE" \
      | head -1 | awk '{print $2}' || echo "")
  fi

  if [[ "$ceiling" =~ ^[0-9]+$ ]] && [[ "$ceiling" -gt 0 ]]; then
    echo "$ceiling"
  fi
}

_compose_output_has_cpu_error() {
  local compose_err="$1"
  tr -d '\r' < "$compose_err" | grep -Eqi "range of CPUs is from|only [0-9]+ CPUs available|invalid.*cpu|NanoCPUs"
}

_resolve_compose_files_from_flags() {
  local ds_dir="$1" compose_flags="$2"
  local prev="" token

  for token in $compose_flags; do
    if [[ "$prev" == "-f" ]]; then
      if [[ "$token" == /* ]]; then
        echo "$token"
      else
        echo "${ds_dir}/${token}"
      fi
      prev=""
      continue
    fi
    [[ "$token" == "-f" ]] && prev="-f"
  done
}

_compose_ansi_flag() {
  local compose_cmd="$1"
  case "$compose_cmd" in
    "docker compose") echo "--ansi never" ;;
    "docker-compose") echo "--no-ansi" ;;
    *) echo "" ;;
  esac
}

_compose_list_services() {
  local ds_dir="$1" compose_cmd="$2" compose_flags="$3"
  local ansi_flag cmd
  ansi_flag=$(_compose_ansi_flag "$compose_cmd")
  cmd="${compose_cmd}"
  [[ -n "$ansi_flag" ]] && cmd="${cmd} ${ansi_flag}"
  cmd="${cmd} ${compose_flags} config --services"

  su - "$ODS_USER" -c "cd ${ds_dir} && ${cmd}" 2>>"$LOGFILE"
}

_extract_missing_image_services() {
  local compose_err="$1"
  local matched_lines status=0
  matched_lines=$(tr -d '\r' < "$compose_err" | grep -Ei 'Error manifest for|pull access denied for') || status=$?
  # grep exit: 0 = matched, 1 = no match (expected), >1 = real error
  if (( status > 1 )); then
    warn "grep failed scanning compose stderr for missing-image errors (status ${status})"
  fi
  [[ -z "$matched_lines" ]] && return 0

  local service
  while IFS= read -r line; do
    service=""
    local cleaned="${line//\'/}"
    cleaned="${cleaned//\"/}"
    if [[ "$cleaned" =~ ^[[:space:]]*([a-zA-Z0-9._-]+)[[:space:]]+(Error[[:space:]]+manifest[[:space:]]+for|pull[[:space:]]+access[[:space:]]+denied[[:space:]]+for) ]]; then
      service="${BASH_REMATCH[1]}"
    elif [[ "$cleaned" =~ [Ss]ervice[[:space:]]*([a-zA-Z0-9._-]+) ]]; then
      service="${BASH_REMATCH[1]}"
    elif [[ "$cleaned" =~ ^([a-zA-Z0-9._-]+)[[:space:]]*[\|:] ]]; then
      service="${BASH_REMATCH[1]}"
    fi
    [[ -n "$service" ]] && echo "$service"
  done <<< "$matched_lines" | sort -u
}

_compose_up_with_flags() {
  local ds_dir="$1" compose_cmd="$2" compose_flags="$3" compose_err="$4" up_flags="$5"
  shift 5
  local ansi_flag cmd service_args
  ansi_flag=$(_compose_ansi_flag "$compose_cmd")
  cmd="${compose_cmd}"
  [[ -n "$ansi_flag" ]] && cmd="${cmd} ${ansi_flag}"
  cmd="${cmd} ${compose_flags} up -d"
  [[ -n "$up_flags" ]] && cmd="${cmd} ${up_flags}"
  if [[ "$#" -gt 0 ]]; then
    printf -v service_args ' %q' "$@"
    cmd="${cmd}${service_args}"
  fi

  su - "$ODS_USER" -c "cd ${ds_dir} && ${cmd}" 2>&1 \
    | tee -a "$LOGFILE" | tee "$compose_err"
}

_apply_host_cpu_caps() {
  local ds_dir="$1" env_file="$2" daemon_ceiling="${3:-}" compose_flags="${4:-}"
  local nproc_count docker_ncpu compose_ceiling max_cpu
  local -a compose_files=()

  nproc_count=$(nproc 2>>"$LOGFILE" || echo 1)
  docker_ncpu=$(docker info --format '{{.NCPU}}' 2>>"$LOGFILE" || echo "unknown")
  compose_ceiling=$(get_compose_cpu_ceiling)
  max_cpu=$(compute_safe_cpu_cap "$daemon_ceiling")

  cap_cpu_in_yaml "$ds_dir" "$max_cpu"
  if [[ -n "$compose_flags" ]]; then
    mapfile -t compose_files < <(_resolve_compose_files_from_flags "$ds_dir" "$compose_flags")
    if [[ "${#compose_files[@]}" -gt 0 ]]; then
      cap_cpu_in_files "$max_cpu" "${compose_files[@]}"
    fi
  fi
  _set_safe_llama_cpu_caps "$env_file" "$max_cpu"
  log "Ensured compose CPU limits <= ${max_cpu} cores (nproc=${nproc_count}, docker=${docker_ncpu}, ceiling=${compose_ceiling}${daemon_ceiling:+, daemon=${daemon_ceiling}})"
}

_compose_up() {
  local ds_dir="$1" compose_cmd="$2" compose_flags="$3" compose_err="$4"
  shift 4
  local ansi_flag cmd service_args
  ansi_flag=$(_compose_ansi_flag "$compose_cmd")
  cmd="${compose_cmd}"
  [[ -n "$ansi_flag" ]] && cmd="${cmd} ${ansi_flag}"
  cmd="${cmd} ${compose_flags} up -d"
  if [[ "$#" -gt 0 ]]; then
    printf -v service_args ' %q' "$@"
    cmd="${cmd}${service_args}"
  fi

  su - "$ODS_USER" -c "cd ${ds_dir} && ${cmd}" 2>&1 \
    | tee -a "$LOGFILE" | tee "$compose_err"
}

_compose_up_with_cpu_heal() {
  local ds_dir="$1" compose_cmd="$2" compose_flags="$3" env_file="$4" scope="$5"
  shift 5
  local compose_err daemon_ceiling
  compose_err=$(mktemp)

  if _compose_up "$ds_dir" "$compose_cmd" "$compose_flags" "$compose_err" "$@"; then
    rm -f "$compose_err"
    return 0
  fi

  if _compose_output_has_cpu_error "$compose_err"; then
    daemon_ceiling=$(_extract_cpu_ceiling_from_compose_error "$compose_err")
    if [[ -n "$daemon_ceiling" ]]; then
      warn "CPU limit exceeds daemon ceiling (${daemon_ceiling}) during ${scope} — recapping and retrying"
    else
      warn "CPU limit exceeds host/daemon cores during ${scope} — recapping and retrying"
    fi
    _apply_host_cpu_caps "$ds_dir" "$env_file" "$daemon_ceiling" "$compose_flags"
    if _compose_up "$ds_dir" "$compose_cmd" "$compose_flags" "$compose_err" "$@"; then
      rm -f "$compose_err"
      return 0
    fi
  fi

  local missing_services
  missing_services=$(_extract_missing_image_services "$compose_err")
  if [[ -n "$missing_services" ]]; then
    local missing_list
    missing_list="${missing_services//$'\n'/, }"
    warn "Compose failed due to missing images for services: ${missing_list}"
    local service_output
    if ! service_output=$(_compose_list_services "$ds_dir" "$compose_cmd" "$compose_flags"); then
      warn "Failed to list compose services after missing-image error (non-fatal)"
    else
      local -A missing_map=()
      local -a filtered_services=()
      local service
      while IFS= read -r service; do
        [[ -n "$service" ]] && missing_map["$service"]=1
      done <<< "$missing_services"
      while IFS= read -r service; do
        [[ -z "$service" ]] && continue
        [[ -n "${missing_map[$service]:-}" ]] && continue
        filtered_services+=("$service")
      done <<< "$service_output"

      if [[ "${#filtered_services[@]}" -gt 0 ]]; then
        if _compose_up_with_flags "$ds_dir" "$compose_cmd" "$compose_flags" "$compose_err" "--no-deps" "${filtered_services[@]}"; then
          warn "PARTIAL BRING-UP: started ${#filtered_services[@]} services, skipped (missing images): ${missing_list}"
          rm -f "$compose_err"
          return 0
        fi
      fi
    fi
  fi

  rm -f "$compose_err"
  return 1
}

_heal_dashboard_api_proxy() {
  local env_file="$1"
  local dashboard_port dashboard_api_port dash_status api_status
  dashboard_port=$(env_get "$env_file" "DASHBOARD_PORT")
  dashboard_port="${dashboard_port:-3001}"
  dashboard_api_port=$(env_get "$env_file" "DASHBOARD_API_PORT")
  dashboard_api_port="${dashboard_api_port:-3002}"

  dash_status=$(docker inspect --format '{{.State.Status}}' ods-dashboard 2>/dev/null || echo "missing") # stderr expected: container may not exist
  api_status=$(docker inspect --format '{{.State.Status}}' ods-dashboard-api 2>/dev/null || echo "missing") # stderr expected: container may not exist
  [[ "$dash_status" != "running" || "$api_status" != "running" ]] && return 0

  if curl -sf --max-time 3 "http://127.0.0.1:${dashboard_api_port}/health" >/dev/null 2>&1 \
    && ! curl -sf --max-time 4 "http://127.0.0.1:${dashboard_port}/api/status" >/dev/null 2>&1; then
    warn "Dashboard returned API 502 while dashboard-api is healthy — restarting dashboard to refresh upstream"
    # [NON-FATAL: dashboard] Individual service failure does not block others.
    docker restart ods-dashboard 2>>"$LOGFILE" || warn "dashboard restart failed (non-fatal)"
  fi
}

# Start ODS services via compose
start_services() {
  local ds_dir="$1"
  local gpu_backend="${2:-auto}"
  local env_file="${ds_dir}/.env"
  local compose_cmd
  compose_cmd=$(get_compose_cmd)

  cd "$ds_dir" || exit 1
  [[ "$gpu_backend" == "auto" ]] && gpu_backend=$(detect_gpu_backend)
  if [[ -z "${GPU_BACKEND:-}" ]]; then
    GPU_BACKEND="$gpu_backend"
  fi

  # Last-resort .env permission guard (fatal if fails — compose cannot start without readable .env)
  if [[ -f "$env_file" ]]; then
    # Check and fix ownership independently
    if [[ "$(stat -c '%U' "$env_file" 2>>"$LOGFILE" || echo root)" != "${ODS_USER}" ]]; then
      chown "${ODS_USER}:${ODS_USER}" "$env_file" || {
        err ".env ownership fix failed in start_services — Docker Compose cannot start"
        exit 1
      }
    fi
    # Check and fix mode independently
    if [[ "$(stat -c '%a' "$env_file" 2>>"$LOGFILE")" != "660" ]]; then
      chmod 0660 "$env_file" || {
        err ".env chmod to 0660 failed in start_services — Docker Compose cannot start"
        exit 1
      }
    fi
  fi

  local gpu_overlay="docker-compose.${gpu_backend}.yml"
  if [[ ! -f "$gpu_overlay" && "$gpu_backend" != "cpu" ]]; then
    warn "GPU overlay ${gpu_overlay} not found — falling back to nvidia"
    gpu_overlay="docker-compose.nvidia.yml"
  fi

  local compose_flags="-f docker-compose.base.yml"
  if [[ "$gpu_backend" != "cpu" && -f "$gpu_overlay" ]]; then
    compose_flags="${compose_flags} -f ${gpu_overlay}"
  fi

  # Prefer upstream compose stack resolver
  if [[ -x "${ds_dir}/scripts/resolve-compose-stack.sh" ]]; then
    log "Using ODS's resolve-compose-stack.sh"
    local resolved_flags
    resolved_flags=$(su - "$ODS_USER" -c \
      "cd ${ds_dir} && ./scripts/resolve-compose-stack.sh \
        --gpu-backend ${gpu_backend} --gpu-count ${GPU_COUNT:-1}" 2>&1 || echo "")
    if [[ -n "$resolved_flags" ]]; then
      compose_flags="$resolved_flags"
    fi
  fi

  _generate_p2p_gpu_overlay "$ds_dir"
  if [[ -f "${ds_dir}/docker-compose.p2p-gpu.yml" ]]; then
    compose_flags="${compose_flags} -f docker-compose.p2p-gpu.yml"
  fi

  _cleanup_stale_network
  _apply_host_cpu_caps "$ds_dir" "$env_file" "" "$compose_flags"
  expose_ports_for_vastai "$ds_dir"

  if ! _compose_up_with_cpu_heal "$ds_dir" "$compose_cmd" "$compose_flags" "$env_file" "full compose"; then
    warn "Full compose failed — trying core services only"
    if ! _compose_up_with_cpu_heal "$ds_dir" "$compose_cmd" "$compose_flags" "$env_file" \
      "core services" llama-server dashboard-api open-webui dashboard; then
      warn "Core compose with llama failed — bringing up control plane only"
      # [NON-FATAL: compose] Fallback failure still allows manual recovery.
      _compose_up_with_cpu_heal "$ds_dir" "$compose_cmd" "$compose_flags" "$env_file" \
        "control-plane services" dashboard-api dashboard open-webui \
        || warn "control-plane compose up also failed (non-fatal)"
    fi
  fi

  local normalized_ports
  normalized_ports=$(_normalize_dashboard_api_port_envs "$env_file")
  if [[ -n "$normalized_ports" ]]; then
    log "Normalized commented port env values in .env: ${normalized_ports//$'\n'/, }"
    # [NON-FATAL: dashboard] Individual service failure does not block others.
    docker restart ods-dashboard-api 2>>"$LOGFILE" || warn "dashboard-api restart failed (non-fatal)"
    # [NON-FATAL: dashboard] Individual service failure does not block others.
    docker restart ods-dashboard 2>>"$LOGFILE" || warn "dashboard restart failed (non-fatal)"
  fi

  # If compose exited early, some containers may be left in Created state.
  # Try to start them so users can still reach the control plane.
  local created
  created=$(docker ps -a --filter "status=created" --format '{{.Names}}' | grep '^ods-' || echo "")
  if [[ -n "$created" ]]; then
    warn "Some containers are still in Created state — attempting docker start"
    while IFS= read -r cname; do
      [[ -z "$cname" ]] && continue
      # [NON-FATAL: service] Individual service failure does not block others.
      docker start "$cname" >/dev/null 2>&1 || warn "start ${cname} failed (non-fatal)"
    done <<< "$created"
  fi

  # Nudge dashboard if stuck in Created state
  if docker ps -a --format '{{.Names}} {{.Status}}' 2>&1 | grep -q 'ods-dashboard Created'; then
    # [NON-FATAL: dashboard] Individual service failure does not block others.
    docker start ods-dashboard || warn "dashboard kick failed (non-fatal)"
    log "Kicked dashboard out of Created state"
  fi

  _heal_dashboard_api_proxy "$env_file"
  _ensure_host_agent_network_binding "$ds_dir"
  # [NON-FATAL: host-agent] Agent availability only affects background downloads.
  _ensure_host_agent_running "$ds_dir" || warn "Host agent unavailable - model downloads may fail until agent is started manually"
  # [NON-FATAL: opencode] Optional service; failures do not block others.
  _ensure_opencode_web_running "$ds_dir" || warn "OpenCode web unavailable (non-fatal)"
}
