server_name: ods-nats
port: 4222
http: 8222
max_payload: $NATS_MAX_PAYLOAD
write_deadline: "10s"

authorization {
  timeout: 2
  users: [
    {
      user: $NATS_USER
      password: $NATS_PASSWORD
    }
  ]
}

jetstream {
  store_dir: "/data/jetstream"
  max_memory_store: $NATS_JETSTREAM_MAX_MEMORY
  max_file_store: $NATS_JETSTREAM_MAX_FILE
  encryption_key: $NATS_JETSTREAM_KEY
  cipher: chacha
  strict: true
  sync_interval: "30s"
}
